- name: play level variables
  hosts: local
  become: true
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10HRS
    Trainer: siva kumar
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}, Duration: {{ DURATION }}, {{ Trainer }}"
