# - name: play level variables
#   hosts: local
#   connection: local
#   vars: 
#     COURSE: ansible
#     DURATION: 10HRS
#     Trainer: somayya
#   tasks:
#   - name: print the course info
#     ansible.builtin.debug:
#       msg: "Course Name is: {{ COURSE}}, Duration: {{ DURATION}}, Trainer: {{Trainer }}"

- name: play level variables
  hosts: local
  become: true
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10HRS
    Trainer: siva kumar
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}, Duration: {{ DURATION }}, {{ Trainer }}"
